version: "3.0"

services:
    nginx:
        image: nginx
        ports: 
          - 8005:80
        volumes:
          - ./code:/code
          - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
          - backend
          - frontend
    php:
        image: "php:7-fpm"
        networks:
          - backend
        volumes:
          - ./code:/code

    
    
    mysql:
        image: mysql/mysql-server:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
          - ./db:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: root
        networks:
          - backend
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
          - 6001:80
        environment:
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: root
          PMA_HOST: mysql
        networks:
          - backend
     

   
networks:
    frontend:
    backend:
