version: "3.0"
#serwisy
services:
#serwer nginx mapowanie na port 8005, podłączone 2 woluminy folder code z plikiem index.php i plik konfiguracyjny site.conf, podłączony do 2 sieci backend i frontend
    nginx:
        image: nginx
        ports: 
          - 8005:80
        volumes:
          - ./code:/code
          - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
          - backend
          - frontend
     #php fpm w wersji 7, podłączony do sieci backend
    php:
        image: "php:7-fpm"
        networks:
          - backend
        volumes:
          - ./code:/code

    
    #serwis mysql
    mysql:
        image: mysql/mysql-server:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
          - ./db:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: root
        networks:
          - backend
    #serwis phpmyadmin mapowanie na port 6001
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
          - 6001:80
        environment:
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: root
          PMA_HOST: mysql
        networks:
          - backend
     

   
networks:
    frontend:
    backend:
